server:
  port: 9090
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8585/eureka}
spring:
  cloud:
    gateway:
      globalcors:
          corsConfigurations:
            '[/**]':
              allowedOrigins:
              - "http://localhost:3000"
              allowedHeaders: "*"
              allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
      discovery:
        locator:
          enabled: true
      routes:
        - id: catalogo-service
          uri: lb://catalogo-service
          predicates:
            - Path=/categoria/**,/producto/**
        - id: cliente-service
          uri: lb://cliente-service
          predicates:
            - Path=/cliente/**
        - id: venta-service
          uri: lb://venta-service
          predicates:
            - Path=/venta/**
        - id: imagen-service
          uri: lb://imagen-service
          predicates:
            - Path=/imagen/**